//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCCM.Entidad
{
    using System;
    
    public partial class CatalogoUsuarioResult
    {
        public int TN_ID_Usuario { get; set; }
        public string TC_Identificacion { get; set; }
        public string TC_Nombre_Completo { get; set; }
    }
}
