//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCCM.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMCCM_Entidad_Arma
    {
        public int TN_ID_Arma { get; set; }
        public Nullable<int> TN_ID_Caso { get; set; }
        public Nullable<int> TN_ID_Marca_Arma { get; set; }
        public Nullable<int> TN_ID_Icono_Arma { get; set; }
        public Nullable<int> TN_ID_Tipo_Arma { get; set; }
        public string TC_Modelo_Arma { get; set; }
        public string TC_Calibre { get; set; }
        public string TC_Serie { get; set; }
        public Nullable<System.DateTime> TF_Fecha_Creacion { get; set; }
        public Nullable<System.DateTime> TF_Fecha_Modificacion { get; set; }
        public string TC_Creado_Por { get; set; }
        public string TC_Modificado_Por { get; set; }
        public Nullable<bool> TB_Eliminado { get; set; }
        public Nullable<bool> TB_Verificado { get; set; }
        public string TC_Comentario { get; set; }
    
        public virtual TMCCM_C_Arma_Icono_Arma TMCCM_C_Arma_Icono_Arma { get; set; }
        public virtual TMCCM_C_Arma_Marca TMCCM_C_Arma_Marca { get; set; }
        public virtual TMCCM_C_Arma_Tipo_Arma TMCCM_C_Arma_Tipo_Arma { get; set; }
        public virtual TMCCM_Caso TMCCM_Caso { get; set; }
    }
}
