//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCCM.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMCCM_Caso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TMCCM_Caso()
        {
            this.TMCCM_Entidad_Droga = new HashSet<TMCCM_Entidad_Droga>();
            this.TMCCM_Entidad_Telefono = new HashSet<TMCCM_Entidad_Telefono>();
            this.TMCCM_Entidad_Ubicacion = new HashSet<TMCCM_Entidad_Ubicacion>();
            this.TMCCM_Evento = new HashSet<TMCCM_Evento>();
            this.TMCCM_Gasto = new HashSet<TMCCM_Gasto>();
            this.TMCCM_Grupo = new HashSet<TMCCM_Grupo>();
            this.TMCCM_Tarea = new HashSet<TMCCM_Tarea>();
            this.TMCCM_Entidad_Arma = new HashSet<TMCCM_Entidad_Arma>();
            this.TMCCM_Entidad_Persona = new HashSet<TMCCM_Entidad_Persona>();
            this.TMCCM_Entidad_Persona_Juridica = new HashSet<TMCCM_Entidad_Persona_Juridica>();
            this.TMCCM_Entidad_Vehiculo = new HashSet<TMCCM_Entidad_Vehiculo>();
        }
    
        public int TN_ID_Caso { get; set; }
        public Nullable<int> TN_ECU { get; set; }
        public string TC_Nombre_Caso { get; set; }
        public string TC_Enfoque_Trabajo { get; set; }
        public string TC_Area_Trabajo { get; set; }
        public Nullable<int> TN_Nivel { get; set; }
        public string TC_Descripcion { get; set; }
        public string TC_Fuente { get; set; }
        public Nullable<bool> TB_Eliminado { get; set; }
        public string TC_Delito { get; set; }
        public Nullable<System.DateTime> TF_Fecha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TMCCM_Entidad_Droga> TMCCM_Entidad_Droga { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TMCCM_Entidad_Telefono> TMCCM_Entidad_Telefono { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TMCCM_Entidad_Ubicacion> TMCCM_Entidad_Ubicacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TMCCM_Evento> TMCCM_Evento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TMCCM_Gasto> TMCCM_Gasto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TMCCM_Grupo> TMCCM_Grupo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TMCCM_Tarea> TMCCM_Tarea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TMCCM_Entidad_Arma> TMCCM_Entidad_Arma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TMCCM_Entidad_Persona> TMCCM_Entidad_Persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TMCCM_Entidad_Persona_Juridica> TMCCM_Entidad_Persona_Juridica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TMCCM_Entidad_Vehiculo> TMCCM_Entidad_Vehiculo { get; set; }
    }
}
