//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCCM.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMCCM_Evento
    {
        public int TN_ID_Evento { get; set; }
        public Nullable<int> TN_ID_Caso { get; set; }
        public Nullable<System.DateTime> TF_Fecha { get; set; }
        public string TC_Informa { get; set; }
        public string TC_Lugar { get; set; }
        public string TC_Novedad { get; set; }
        public Nullable<bool> TB_Eliminado { get; set; }
    
        public virtual TMCCM_Caso TMCCM_Caso { get; set; }
    }
}
