//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCCM.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMCCM_Entidad_Droga
    {
        public int TN_ID_Droga { get; set; }
        public Nullable<int> TN_ID_Caso { get; set; }
        public Nullable<int> TN_ID_Tipo_Droga { get; set; }
        public string TC_Nombre { get; set; }
        public string TC_Detalle { get; set; }
        public Nullable<int> TN_Cantidad { get; set; }
        public Nullable<System.DateTime> TF_Fecha_Decomiso { get; set; }
        public Nullable<System.TimeSpan> TF_Hora_Decomiso { get; set; }
        public Nullable<bool> TB_Eliminado { get; set; }
        public Nullable<System.DateTime> TF_Fecha_Creacion { get; set; }
        public Nullable<System.DateTime> TF_Fecha_Modificacion { get; set; }
        public string TC_Creado_Por { get; set; }
        public string TC_Modificado_Por { get; set; }
        public Nullable<bool> TB_Verificado { get; set; }
    
        public virtual TMCCM_C_Droga_Tipo_Droga TMCCM_C_Droga_Tipo_Droga { get; set; }
        public virtual TMCCM_Caso TMCCM_Caso { get; set; }
    }
}
