//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCCM.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMCCM_Vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TMCCM_Vehiculo()
        {
            this.TMCCM_Grupo_Vehiculo = new HashSet<TMCCM_Grupo_Vehiculo>();
        }
    
        public int TN_ID_Vehiculo { get; set; }
        public string TC_Placa { get; set; }
        public string TC_Marca { get; set; }
        public string TC_Clase { get; set; }
        public byte[] TB_Fotografia { get; set; }
        public string TC_Clasificacion { get; set; }
        public string TC_Estilo { get; set; }
        public Nullable<int> TN_Anno { get; set; }
        public Nullable<bool> TB_Eliminado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TMCCM_Grupo_Vehiculo> TMCCM_Grupo_Vehiculo { get; set; }
    }
}
